	<?php get_header(); ?>
	<?php get_template_part('pages/block_after_header'); ?>
	<?php get_template_part('pages/block_video'); ?>
	<?php get_template_part('pages/method_block'); ?>
	<?php get_template_part('pages/gallery_block'); ?>
	<?php get_template_part('pages/services_block'); ?>
	<?php get_template_part('pages/blog_block'); ?>
	<?php get_template_part('pages/contact_block'); ?>
	<?php get_template_part('pages/map_block'); ?>
	<?php get_footer(); ?>